# For in the <title>
name: SABnzbd

# Needs to be a string, for string-comparison
wiki_version: '2.3'

# For downloads page. Needs the full x.x.x notation!
# Needs to be a string, for string-comparison
latest_stable: '2.3.9'
latest_testing: '3.0.0RC2'

# Basic ad-URL
ad_link: 'https://www.newshosting.com/usenet/partners/sabnzbd/?a_aid=sabnzbd'

# Extra plugins
plugins:
  - jekyll-redirect-from

# Template settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: SABnzbd.org
  -
    scope:
      path: "wiki"
    values:
      layout: "wiki"
      section: "Wiki"
