# For in the <title>
name: SABnzbd

# Needs to be a string, for string-comparison
wiki_version: '3.6'

# For downloads page. Needs the full x.x.x notation!
# Needs to be a string, for string-comparison
latest_stable: '3.6.1'
latest_testing: ''

# Basic ad-URL
ad_link: 'https://www.newshosting.com/partners/exclusive-usenet-offer/?a_aid=sabnzbd'

# Extra plugins
plugins:
  - jekyll-redirect-from

exclude:
  - .jekyll-cache/
  - README.md
  - LICENSE.md
  - "*.psd"

keep_files:
  - css/
  - fonts/
  - images/
  - js/
  - tests/

# Template settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: SABnzbd.org
  -
    scope:
      path: "wiki"
    values:
      layout: "wiki"
      section: "Wiki"
